language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
- 'export DISPLAY=:99.0'
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm i
script: npm run test
env:
  - CXX=g++-4.8
